name: Deploy CMS NextJS Application

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
          
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t duymt3/happyboard-cms .  
      - name: Publish image to docker hub
        run: docker push duymt3/happyboard-cms:latest
        
  # deploy:
  #   needs: build
  #   runs-on: cicd-be
  #   steps:
  #     - name: Pull image from docker hub
  #       run: docker pull duymt3/happyboard-cms:latest
  #     - name: Delete old container
  #       run: docker rm -f happyboard-cms-container
  #     - name: Delete old image
  #       run: docker rmi duymt3/happyboard-cms:latest
  #     - name: Run docker container
  #       run: docker run -d -p 3000:3000 --name happyboard-cms-container duymt3/happyboard-cms:latest
